name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.24.2+2
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 国际化 https://pub.flutter-io.cn/packages/intl
  intl: ^0.16.1
  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^3.0.10
  # rx https://pub.flutter-io.cn/packages/rxdart
  rxdart: ^0.25.0
  # 图片加载增强 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^2.5.0
  # toast https://pub.flutter-io.cn/packages/oktoast
  oktoast: ^2.3.2
  # 模态对话框增强 https://pub.flutter-io.cn/packages/modal_bottom_sheet
  modal_bottom_sheet: ^1.0.0+1
  # 日志打印 https://pub.flutter-io.cn/packages/logger
  logger: ^0.9.4
  # 获取路径 https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^1.6.27

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
