name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.18.4
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 国际化
  intl: 0.16.1
  # 网络请求
  dio: 3.0.9
  # rx
  rxdart: 0.24.1
  # di
  kiwi: 2.0.0
  # 加解密
  encrypt: 4.0.2
  crypto: 2.1.4
  # 图片加载增强
  cached_network_image: 2.2.0+1
  # toast
  oktoast: 2.3.2
  # svg
  flutter_svg: 0.18.0
  # 模态对话框增强
  modal_bottom_sheet: 0.2.0+1
  # 日志打印
  logger_flutter: 0.7.1
  logger: 0.7.0+2

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter